# Generated by Neurodocker and Reproenv.

FROM debian:bullseye-slim
ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq \
           && apt-get install -y -q --no-install-recommends \
                  ca-certificates \
                  curl \
                  git \
                  unzip \
           && rm -rf /var/lib/apt/lists/*
RUN curl -fsSL https://deno.land/install.sh | env DENO_INSTALL=/usr/local sh -s -- --no-modify-path
RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR=/usr/local/bin INSTALLER_NO_MODIFY_PATH=1 sh
ENV UV_LINK_MODE="copy"
ENV UV_PYTHON_INSTALL_DIR="/opt/uv-python"
ENV UV_PROJECT_ENVIRONMENT="/home/ffrprep/.venv"
ENV PYTHONDONTWRITEBYTECODE="1"
COPY [".", \
      "/home/ffrprep"]
WORKDIR /home/ffrprep
RUN uv sync --frozen --no-dev
RUN chmod +x /home/ffrprep/ffrprep-entrypoint.sh
RUN chmod -R a+rX /opt/uv-python /home/ffrprep/.venv
RUN chmod -R a+rwX /home/ffrprep
ENV IS_DOCKER="1"
WORKDIR /tmp
ENTRYPOINT ["/home/ffrprep/ffrprep-entrypoint.sh"]

# Save specification to JSON.
RUN printf '{ \
  "pkg_manager": "apt", \
  "existing_users": [ \
    "root" \
  ], \
  "instructions": [ \
    { \
      "name": "from_", \
      "kwds": { \
        "base_image": "debian:bullseye-slim" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "LANG": "en_US.UTF-8", \
        "LC_ALL": "en_US.UTF-8", \
        "ND_ENTRYPOINT": "/neurodocker/startup.sh" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "export ND_ENTRYPOINT=\\"/neurodocker/startup.sh\\"\\napt-get update -qq\\napt-get install -y -q --no-install-recommends \\\\\\n    apt-utils \\\\\\n    bzip2 \\\\\\n    ca-certificates \\\\\\n    curl \\\\\\n    locales \\\\\\n    unzip\\nrm -rf /var/lib/apt/lists/*\\nsed -i -e '"'"'s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/'"'"' /etc/locale.gen\\ndpkg-reconfigure --frontend=noninteractive locales\\nupdate-locale LANG=\\"en_US.UTF-8\\"\\nchmod 777 /opt && chmod a+s /opt\\nmkdir -p /neurodocker\\nif [ ! -f \\"$ND_ENTRYPOINT\\" ]; then\\n  echo '"'"'#!/usr/bin/env bash'"'"' >> \\"$ND_ENTRYPOINT\\"\\n  echo '"'"'set -e'"'"' >> \\"$ND_ENTRYPOINT\\"\\n  echo '"'"'export USER=\\"${USER:=`whoami`}\\"'"'"' >> \\"$ND_ENTRYPOINT\\"\\n  echo '"'"'if [ -n \\"$1\\" ]; then \\"$@\\"; else /usr/bin/env bash; fi'"'"' >> \\"$ND_ENTRYPOINT\\";\\nfi\\nchmod -R 777 /neurodocker && chmod a+s /neurodocker" \
      } \
    }, \
    { \
      "name": "arg", \
      "kwds": { \
        "key": "DEBIAN_FRONTEND", \
        "value": "noninteractive" \
      } \
    }, \
    { \
      "name": "install", \
      "kwds": { \
        "pkgs": [ \
          "ca-certificates", \
          "curl", \
          "unzip", \
          "git" \
        ], \
        "opts": null \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "apt-get update -qq \\\\\\n    && apt-get install -y -q --no-install-recommends \\\\\\n           ca-certificates \\\\\\n           curl \\\\\\n           git \\\\\\n           unzip \\\\\\n    && rm -rf /var/lib/apt/lists/*" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "curl -fsSL https://deno.land/install.sh | env DENO_INSTALL=/usr/local sh -s -- --no-modify-path" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR=/usr/local/bin INSTALLER_NO_MODIFY_PATH=1 sh" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "UV_LINK_MODE": "copy" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "UV_PYTHON_INSTALL_DIR": "/opt/uv-python" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "UV_PROJECT_ENVIRONMENT": "/home/ffrprep/.venv" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "PYTHONDONTWRITEBYTECODE": "1" \
      } \
    }, \
    { \
      "name": "copy", \
      "kwds": { \
        "source": [ \
          ".", \
          "/home/ffrprep" \
        ], \
        "destination": "/home/ffrprep" \
      } \
    }, \
    { \
      "name": "workdir", \
      "kwds": { \
        "path": "/home/ffrprep" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "uv sync --frozen --no-dev" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "chmod +x /home/ffrprep/ffrprep-entrypoint.sh" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "chmod -R a+rX /opt/uv-python /home/ffrprep/.venv" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "chmod -R a+rwX /home/ffrprep" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "IS_DOCKER": "1" \
      } \
    }, \
    { \
      "name": "workdir", \
      "kwds": { \
        "path": "/tmp" \
      } \
    }, \
    { \
      "name": "entrypoint", \
      "kwds": { \
        "args": [ \
          "/home/ffrprep/ffrprep-entrypoint.sh" \
        ] \
      } \
    } \
  ] \
}' > /.reproenv.json
# End saving to specification to JSON.
